language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore
 - dotnet build /home/travis/build/swiftyspiffy/TwitchLib/TwitchLib.Logging/Provider.Log4Net/Provider.Log4Net.csproj
 - dotnet build /home/travis/build/swiftyspiffy/TwitchLib/TwitchLib.Logging/Providers.NLog/Provider.NLog.csproj
 - dotnet build /home/travis/build/swiftyspiffy/TwitchLib/TwitchLib.Logging/Providers.SeriLog/Provider.SeriLog.csproj
 - dotnet build /home/travis/build/swiftyspiffy/TwitchLib/TwitchLib/TwitchLib.csproj

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5